CREATE TABLE IF NOT EXISTS CLIENT (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT,
    PHONE NUMBER TEXT,
    CITY TEXT);
)
INSERT INTO CLIENT (NAME,PHONE,CITY) VALUES(?,?,?);
SELECT NAME,PHONE,ID FROM CLIENT;